// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CategoryName string `gorm:"column:category_name;not null" json:"category_name"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
