// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

const TableNameFeedback = "feedback"

// Feedback mapped from table <feedback>
type Feedback struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       string `gorm:"column:uid;not null" json:"uid"`
	Title     string `gorm:"column:title;not null" json:"title"`
	Content   string `gorm:"column:content;not null" json:"content"`
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt int64  `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Feedback's table name
func (*Feedback) TableName() string {
	return TableNameFeedback
}
