// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID            string `gorm:"column:uid;not null" json:"uid"`
	Data           string `gorm:"column:data;not null" json:"data"`
	ConversationID string `gorm:"column:conversation_id;not null" json:"conversation_id"`
	RecipientID    string `gorm:"column:recipient_id;not null" json:"recipient_id"`
	MessageID      string `gorm:"column:message_id;not null" json:"message_id"`
	Category       string `gorm:"column:category;not null" json:"category"`
	CreatedAt      int64  `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
