// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

const TableNameRefund = "refund"

// Refund mapped from table <refund>
type Refund struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       string `gorm:"column:uid;not null" json:"uid"`
	AssetID   string `gorm:"column:asset_id;not null" json:"asset_id"`
	TraceID   string `gorm:"column:trace_id;not null" json:"trace_id"`
	Price     string `gorm:"column:price;not null;default:0.00000000;comment:退款金额" json:"price"` // 退款金额
	Select    bool   `gorm:"column:select;not null;comment:选择" json:"select"`                    // 选择
	Memo      string `gorm:"column:memo;not null" json:"memo"`
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName Refund's table name
func (*Refund) TableName() string {
	return TableNameRefund
}
