// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

const TableNameSnapshot = "snapshot"

// Snapshot mapped from table <snapshot>
type Snapshot struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TraceID        string `gorm:"column:trace_id;not null" json:"trace_id"`
	Memo           string `gorm:"column:memo;not null" json:"memo"`
	Type           string `gorm:"column:type;not null" json:"type"`
	SnapshotID     string `gorm:"column:snapshot_id;not null" json:"snapshot_id"`
	OpponentID     string `gorm:"column:opponent_id;not null" json:"opponent_id"`
	AssetID        string `gorm:"column:asset_id;not null" json:"asset_id"`
	Amount         string `gorm:"column:amount;not null" json:"amount"`
	OpeningBalance string `gorm:"column:opening_balance;not null" json:"opening_balance"`
	ClosingBalance string `gorm:"column:closing_balance;not null" json:"closing_balance"`
	CreatedAt      string `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName Snapshot's table name
func (*Snapshot) TableName() string {
	return TableNameSnapshot
}
