// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

const TableNameTopicPurchase = "topic_purchases"

// TopicPurchase mapped from table <topic_purchases>
type TopicPurchase struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       string `gorm:"column:uid;not null" json:"uid"`
	Tid       int64  `gorm:"column:tid;not null" json:"tid"`
	YesPrice  string `gorm:"column:yes_price;not null;default:0.00000000;comment:支持金额" json:"yes_price"` // 支持金额
	NoPrice   string `gorm:"column:no_price;not null;default:0.00000000;comment:反对金额" json:"no_price"`   // 反对金额
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt int64  `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName TopicPurchase's table name
func (*TopicPurchase) TableName() string {
	return TableNameTopicPurchase
}
