version: "1.0"
services:
  mongo:
    image: mongo:6-jammy
    container_name: betxin-mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongodb:/data/db

  cache:
    image: redis:6.2-alpine
    container_name: betxin-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb:
    driver: local
  cache:
    driver: local
