// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IdentityNumber string `gorm:"column:identity_number;not null" json:"identity_number"`
	UID            string `gorm:"column:uid;not null" json:"uid"`
	FullName       string `gorm:"column:full_name" json:"full_name"`
	AvatarURL      string `gorm:"column:avatar_url" json:"avatar_url"`
	SessionID      string `gorm:"column:session_id" json:"session_id"`
	Biography      string `gorm:"column:biography" json:"biography"`
	PrivateKey     string `gorm:"column:private_key" json:"private_key"`
	ClientID       string `gorm:"column:client_id" json:"client_id"`
	Contract       string `gorm:"column:contract" json:"contract"`
	IsMvmUser      bool   `gorm:"column:is_mvm_user" json:"is_mvm_user"`
	CreatedAt      int64  `gorm:"column:created_at;not null;autoCreateTime:milli" json:"created_at"`
	UpdatedAt      int64  `gorm:"column:updated_at;not null;autoUpdateTime:milli" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
