name: "web_app"
mode: "dev"
port: 9091
version: "v0.1.3"
start_time: "2020-07-01"
machine_id: 1
driver: "mysql"

log:
  console_logging_enabled: true 
  encode_logs_as_json: true 
  file_logging_enabled: true
  directory: "./log"
  filename: "betxin.log"
  max_size: 1
  max_backups: 3
  max_age: 7
  level: -1
  local_time: true
  compress: false

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "betxin_test"
  max_open_conns: 200
  max_idel_conns: 50

mongo:
  host: "127.0.0.1"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100
