// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lixvyang/betxin.one/internal/model/database/mysql/dal/sqlmodel"
)

func newCollect(db *gorm.DB, opts ...gen.DOOption) collect {
	_collect := collect{}

	_collect.collectDo.UseDB(db, opts...)
	_collect.collectDo.UseModel(&sqlmodel.Collect{})

	tableName := _collect.collectDo.TableName()
	_collect.ALL = field.NewAsterisk(tableName)
	_collect.ID = field.NewInt32(tableName, "id")
	_collect.UID = field.NewString(tableName, "uid")
	_collect.Tid = field.NewInt64(tableName, "tid")
	_collect.Status = field.NewBool(tableName, "status")
	_collect.CreatedAt = field.NewInt64(tableName, "created_at")
	_collect.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_collect.fillFieldMap()

	return _collect
}

type collect struct {
	collectDo collectDo

	ALL       field.Asterisk
	ID        field.Int32
	UID       field.String
	Tid       field.Int64
	Status    field.Bool // 状态
	CreatedAt field.Int64
	UpdatedAt field.Int64

	fieldMap map[string]field.Expr
}

func (c collect) Table(newTableName string) *collect {
	c.collectDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c collect) As(alias string) *collect {
	c.collectDo.DO = *(c.collectDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *collect) updateTableName(table string) *collect {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.UID = field.NewString(table, "uid")
	c.Tid = field.NewInt64(table, "tid")
	c.Status = field.NewBool(table, "status")
	c.CreatedAt = field.NewInt64(table, "created_at")
	c.UpdatedAt = field.NewInt64(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *collect) WithContext(ctx context.Context) ICollectDo { return c.collectDo.WithContext(ctx) }

func (c collect) TableName() string { return c.collectDo.TableName() }

func (c collect) Alias() string { return c.collectDo.Alias() }

func (c collect) Columns(cols ...field.Expr) gen.Columns { return c.collectDo.Columns(cols...) }

func (c *collect) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *collect) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["uid"] = c.UID
	c.fieldMap["tid"] = c.Tid
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c collect) clone(db *gorm.DB) collect {
	c.collectDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c collect) replaceDB(db *gorm.DB) collect {
	c.collectDo.ReplaceDB(db)
	return c
}

type collectDo struct{ gen.DO }

type ICollectDo interface {
	gen.SubQuery
	Debug() ICollectDo
	WithContext(ctx context.Context) ICollectDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICollectDo
	WriteDB() ICollectDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICollectDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICollectDo
	Not(conds ...gen.Condition) ICollectDo
	Or(conds ...gen.Condition) ICollectDo
	Select(conds ...field.Expr) ICollectDo
	Where(conds ...gen.Condition) ICollectDo
	Order(conds ...field.Expr) ICollectDo
	Distinct(cols ...field.Expr) ICollectDo
	Omit(cols ...field.Expr) ICollectDo
	Join(table schema.Tabler, on ...field.Expr) ICollectDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICollectDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICollectDo
	Group(cols ...field.Expr) ICollectDo
	Having(conds ...gen.Condition) ICollectDo
	Limit(limit int) ICollectDo
	Offset(offset int) ICollectDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICollectDo
	Unscoped() ICollectDo
	Create(values ...*sqlmodel.Collect) error
	CreateInBatches(values []*sqlmodel.Collect, batchSize int) error
	Save(values ...*sqlmodel.Collect) error
	First() (*sqlmodel.Collect, error)
	Take() (*sqlmodel.Collect, error)
	Last() (*sqlmodel.Collect, error)
	Find() ([]*sqlmodel.Collect, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.Collect, err error)
	FindInBatches(result *[]*sqlmodel.Collect, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlmodel.Collect) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICollectDo
	Assign(attrs ...field.AssignExpr) ICollectDo
	Joins(fields ...field.RelationField) ICollectDo
	Preload(fields ...field.RelationField) ICollectDo
	FirstOrInit() (*sqlmodel.Collect, error)
	FirstOrCreate() (*sqlmodel.Collect, error)
	FindByPage(offset int, limit int) (result []*sqlmodel.Collect, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICollectDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c collectDo) Debug() ICollectDo {
	return c.withDO(c.DO.Debug())
}

func (c collectDo) WithContext(ctx context.Context) ICollectDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c collectDo) ReadDB() ICollectDo {
	return c.Clauses(dbresolver.Read)
}

func (c collectDo) WriteDB() ICollectDo {
	return c.Clauses(dbresolver.Write)
}

func (c collectDo) Session(config *gorm.Session) ICollectDo {
	return c.withDO(c.DO.Session(config))
}

func (c collectDo) Clauses(conds ...clause.Expression) ICollectDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c collectDo) Returning(value interface{}, columns ...string) ICollectDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c collectDo) Not(conds ...gen.Condition) ICollectDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c collectDo) Or(conds ...gen.Condition) ICollectDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c collectDo) Select(conds ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c collectDo) Where(conds ...gen.Condition) ICollectDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c collectDo) Order(conds ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c collectDo) Distinct(cols ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c collectDo) Omit(cols ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c collectDo) Join(table schema.Tabler, on ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c collectDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICollectDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c collectDo) RightJoin(table schema.Tabler, on ...field.Expr) ICollectDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c collectDo) Group(cols ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c collectDo) Having(conds ...gen.Condition) ICollectDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c collectDo) Limit(limit int) ICollectDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c collectDo) Offset(offset int) ICollectDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c collectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICollectDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c collectDo) Unscoped() ICollectDo {
	return c.withDO(c.DO.Unscoped())
}

func (c collectDo) Create(values ...*sqlmodel.Collect) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c collectDo) CreateInBatches(values []*sqlmodel.Collect, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c collectDo) Save(values ...*sqlmodel.Collect) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c collectDo) First() (*sqlmodel.Collect, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.Collect), nil
	}
}

func (c collectDo) Take() (*sqlmodel.Collect, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.Collect), nil
	}
}

func (c collectDo) Last() (*sqlmodel.Collect, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.Collect), nil
	}
}

func (c collectDo) Find() ([]*sqlmodel.Collect, error) {
	result, err := c.DO.Find()
	return result.([]*sqlmodel.Collect), err
}

func (c collectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.Collect, err error) {
	buf := make([]*sqlmodel.Collect, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c collectDo) FindInBatches(result *[]*sqlmodel.Collect, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c collectDo) Attrs(attrs ...field.AssignExpr) ICollectDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c collectDo) Assign(attrs ...field.AssignExpr) ICollectDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c collectDo) Joins(fields ...field.RelationField) ICollectDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c collectDo) Preload(fields ...field.RelationField) ICollectDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c collectDo) FirstOrInit() (*sqlmodel.Collect, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.Collect), nil
	}
}

func (c collectDo) FirstOrCreate() (*sqlmodel.Collect, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.Collect), nil
	}
}

func (c collectDo) FindByPage(offset int, limit int) (result []*sqlmodel.Collect, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c collectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c collectDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c collectDo) Delete(models ...*sqlmodel.Collect) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *collectDo) withDO(do gen.Dao) *collectDo {
	c.DO = *do.(*gen.DO)
	return c
}
