// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lixvyang/betxin.one/internal/model/database/mysql/core"
)

func newCollect(db *gorm.DB, opts ...gen.DOOption) collect {
	_collect := collect{}

	_collect.collectDo.UseDB(db, opts...)
	_collect.collectDo.UseModel(&core.Collect{})

	tableName := _collect.collectDo.TableName()
	_collect.ALL = field.NewAsterisk(tableName)
	_collect.ID = field.NewInt64(tableName, "id")
	_collect.UID = field.NewString(tableName, "uid")
	_collect.Tid = field.NewString(tableName, "tid")
	_collect.Status = field.NewBool(tableName, "status")
	_collect.CreatedAt = field.NewTime(tableName, "created_at")
	_collect.UpdatedAt = field.NewTime(tableName, "updated_at")

	_collect.fillFieldMap()

	return _collect
}

type collect struct {
	collectDo

	ALL       field.Asterisk
	ID        field.Int64
	UID       field.String
	Tid       field.String
	Status    field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c collect) Table(newTableName string) *collect {
	c.collectDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c collect) As(alias string) *collect {
	c.collectDo.DO = *(c.collectDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *collect) updateTableName(table string) *collect {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.UID = field.NewString(table, "uid")
	c.Tid = field.NewString(table, "tid")
	c.Status = field.NewBool(table, "status")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *collect) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *collect) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["uid"] = c.UID
	c.fieldMap["tid"] = c.Tid
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c collect) clone(db *gorm.DB) collect {
	c.collectDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c collect) replaceDB(db *gorm.DB) collect {
	c.collectDo.ReplaceDB(db)
	return c
}

type collectDo struct{ gen.DO }

type ICollectDo interface {
	gen.SubQuery
	Debug() ICollectDo
	WithContext(ctx context.Context) ICollectDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICollectDo
	WriteDB() ICollectDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICollectDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICollectDo
	Not(conds ...gen.Condition) ICollectDo
	Or(conds ...gen.Condition) ICollectDo
	Select(conds ...field.Expr) ICollectDo
	Where(conds ...gen.Condition) ICollectDo
	Order(conds ...field.Expr) ICollectDo
	Distinct(cols ...field.Expr) ICollectDo
	Omit(cols ...field.Expr) ICollectDo
	Join(table schema.Tabler, on ...field.Expr) ICollectDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICollectDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICollectDo
	Group(cols ...field.Expr) ICollectDo
	Having(conds ...gen.Condition) ICollectDo
	Limit(limit int) ICollectDo
	Offset(offset int) ICollectDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICollectDo
	Unscoped() ICollectDo
	Create(values ...*core.Collect) error
	CreateInBatches(values []*core.Collect, batchSize int) error
	Save(values ...*core.Collect) error
	First() (*core.Collect, error)
	Take() (*core.Collect, error)
	Last() (*core.Collect, error)
	Find() ([]*core.Collect, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*core.Collect, err error)
	FindInBatches(result *[]*core.Collect, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*core.Collect) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICollectDo
	Assign(attrs ...field.AssignExpr) ICollectDo
	Joins(fields ...field.RelationField) ICollectDo
	Preload(fields ...field.RelationField) ICollectDo
	FirstOrInit() (*core.Collect, error)
	FirstOrCreate() (*core.Collect, error)
	FindByPage(offset int, limit int) (result []*core.Collect, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICollectDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetCollectById(ctx context.Context, id int64) (result *core.Collect, err error)
	GetCollectByTid(ctx context.Context, tid string) (result []*core.Collect, err error)
	GetCollectByUid(ctx context.Context, uid string) (result []*core.Collect, err error)
	GetCollectByUidTid(ctx context.Context, uid string, tid string) (result *core.Collect, err error)
	DeleteCollect(ctx context.Context, tid string, uid string) (err error)
	CreateCollect(ctx context.Context, tid string, uid string) (err error)
}

// SELECT
//
//	*
//
// FROM collect
// WHERE `id` = @id;
func (c collectDo) GetCollectById(ctx context.Context, id int64) (result *core.Collect, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM collect WHERE `id` = ?; ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT
// *
// FROM collect
// WHERE `tid` = @tid AND
// `status` = 1;
func (c collectDo) GetCollectByTid(ctx context.Context, tid string) (result []*core.Collect, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, tid)
	generateSQL.WriteString("SELECT * FROM collect WHERE `tid` = ? AND `status` = 1; ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT
// *
// FROM collect
// WHERE `uid` = @uid AND
// `status` = 1;
func (c collectDo) GetCollectByUid(ctx context.Context, uid string) (result []*core.Collect, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, uid)
	generateSQL.WriteString("SELECT * FROM collect WHERE `uid` = ? AND `status` = 1; ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT
// *
// FROM collect
// WHERE `uid` = @uid AND
// `tid` = @tid AND
// `status` = 1;
func (c collectDo) GetCollectByUidTid(ctx context.Context, uid string, tid string) (result *core.Collect, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, uid)
	params = append(params, tid)
	generateSQL.WriteString("SELECT * FROM collect WHERE `uid` = ? AND `tid` = ? AND `status` = 1; ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// UPDATE  collect SET
// `status` = 0
// WHERE
// `tid` = @tid AND `uid` = @uid;
func (c collectDo) DeleteCollect(ctx context.Context, tid string, uid string) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, tid)
	params = append(params, uid)
	generateSQL.WriteString("UPDATE collect SET `status` = 0 WHERE `tid` = ? AND `uid` = ?; ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// INSERT INTO collect
// (`tid`, `uid`, `status`, `created_at`, `updated_at`)
// VALUES
// (@tid, @uid, 1, NOW(), NOW());
func (c collectDo) CreateCollect(ctx context.Context, tid string, uid string) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, tid)
	params = append(params, uid)
	generateSQL.WriteString("INSERT INTO collect (`tid`, `uid`, `status`, `created_at`, `updated_at`) VALUES (?, ?, 1, NOW(), NOW()); ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (c collectDo) Debug() ICollectDo {
	return c.withDO(c.DO.Debug())
}

func (c collectDo) WithContext(ctx context.Context) ICollectDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c collectDo) ReadDB() ICollectDo {
	return c.Clauses(dbresolver.Read)
}

func (c collectDo) WriteDB() ICollectDo {
	return c.Clauses(dbresolver.Write)
}

func (c collectDo) Session(config *gorm.Session) ICollectDo {
	return c.withDO(c.DO.Session(config))
}

func (c collectDo) Clauses(conds ...clause.Expression) ICollectDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c collectDo) Returning(value interface{}, columns ...string) ICollectDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c collectDo) Not(conds ...gen.Condition) ICollectDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c collectDo) Or(conds ...gen.Condition) ICollectDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c collectDo) Select(conds ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c collectDo) Where(conds ...gen.Condition) ICollectDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c collectDo) Order(conds ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c collectDo) Distinct(cols ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c collectDo) Omit(cols ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c collectDo) Join(table schema.Tabler, on ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c collectDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICollectDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c collectDo) RightJoin(table schema.Tabler, on ...field.Expr) ICollectDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c collectDo) Group(cols ...field.Expr) ICollectDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c collectDo) Having(conds ...gen.Condition) ICollectDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c collectDo) Limit(limit int) ICollectDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c collectDo) Offset(offset int) ICollectDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c collectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICollectDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c collectDo) Unscoped() ICollectDo {
	return c.withDO(c.DO.Unscoped())
}

func (c collectDo) Create(values ...*core.Collect) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c collectDo) CreateInBatches(values []*core.Collect, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c collectDo) Save(values ...*core.Collect) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c collectDo) First() (*core.Collect, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*core.Collect), nil
	}
}

func (c collectDo) Take() (*core.Collect, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*core.Collect), nil
	}
}

func (c collectDo) Last() (*core.Collect, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*core.Collect), nil
	}
}

func (c collectDo) Find() ([]*core.Collect, error) {
	result, err := c.DO.Find()
	return result.([]*core.Collect), err
}

func (c collectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*core.Collect, err error) {
	buf := make([]*core.Collect, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c collectDo) FindInBatches(result *[]*core.Collect, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c collectDo) Attrs(attrs ...field.AssignExpr) ICollectDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c collectDo) Assign(attrs ...field.AssignExpr) ICollectDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c collectDo) Joins(fields ...field.RelationField) ICollectDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c collectDo) Preload(fields ...field.RelationField) ICollectDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c collectDo) FirstOrInit() (*core.Collect, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*core.Collect), nil
	}
}

func (c collectDo) FirstOrCreate() (*core.Collect, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*core.Collect), nil
	}
}

func (c collectDo) FindByPage(offset int, limit int) (result []*core.Collect, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c collectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c collectDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c collectDo) Delete(models ...*core.Collect) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *collectDo) withDO(do gen.Dao) *collectDo {
	c.DO = *do.(*gen.DO)
	return c
}
